### ISSUE TITLE
ルートディレクトリ直下のファイルを一部移動させる

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#106]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
ルートディレクトリ直下のCMake関連のファイル、不要なファイルを下のディレクトリに移動させる。

**Describe alternatives you've considered**

**Additional context**

**Comment by r-kurose** [comment]
トップに cmake フォルダが増えていませんか｡
build の下にはできないのでしょうか｡

**Comment by r-kurose** [comment]
フォルダが移動したことを確認しました｡
