### ISSUE TITLE
Examplesのコンポーネント起動に使うrtc.confが以前のバージョンと内容が違う

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#1112]
**Describe the bug**
インストーラーでインストールした場合に、''C:\Program Files\OpenRTM-aist\2.0.1\Components\C++\Examples\rtc.conf''が1.2.2以前と2.0.0以降で内容が異なっており、ConfigSampleコンポーネントが正常に動作しない。

1.2.2以前のrtc.confは以下の通り。

```
corba.nameservers: localhost
naming.formats: %h.host_cxt/%n.rtc
logger.enable: NO
example.ConsoleOut.config_file: consout.conf
example.ConsoleIn.config_file: consin.conf
example.ConfigSample.config_file: configsample.conf
```

2.0.0以降のrtc.confは以下の通り。

```
corba.nameservers: localhost
naming.formats: %h.host_cxt/%n.rtc
logger.enable: NO
example.ConsoleIn.config_file: consin.conf
```

ConsoleOutコンポーネント起動時にconsout.confを読み込まなくなり、またConfigSampleコンポーネント起動時にconfigsample.confを読み込まなくなっている。
ConsoleOutコンポーネントの動作に影響はないが、ConfigSampleコンポーネントはコンフィギュレーションセットが設定されない問題が発生するため、例えばRTシステムエディタでコンフィギュレーションパラメータを確認すると、以前はdefault、mode1、mode2のコンフィギュレーションセットが見えていたが、2.0.0以降ではdefaultしか見えなくなっている。

**To Reproduce**
1. ConfigSample.batを実行する
2. RTシステムエディタでコンフィギュレーションセットを確認する

**Reproducibility**
100％

**Expected behavior**
コンフィギュレーションセットがdefault、mode1、mode2が設定されるようにする。

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist Version 2.0.0

**Additional context**

**Comment by n-kawauchi** [comment]
この問題はサンプルRTCをcmakeで再生成したことで発生しました。
1.2.2でのrtc.confは、SimpleIOのものが使われています。
https://github.com/OpenRTM/OpenRTM-aist/blob/svn/RELENG_1_2/examples/SimpleIO/rtc.conf

2.0系で再生成したRTCに含まれるrtc.confは、本RTCとは関係ない設定は削除する動作で構わないとのことでしたので
現在の設定になっています。この件、2021/7/19のミーティングで確認しました。この時はConfigSampleコンポーネントの
動作については認識が足りなかったと思います。

1.2.2と同じ動作にするためには、ConfigSampleのrtc.confにconsout.confとconsin.confを追加し、この
rtc.confがインストールされるように修正した方がよいでしょうか。
https://github.com/OpenRTM/OpenRTM-aist/blob/master/examples/ConfigSample/rtc.conf
example.ConsoleOut.config_file: consout.conf
example.ConsoleIn.config_file: consin.conf

**Comment by n-kawauchi** [comment]
了解しました。
