### ISSUE TITLE
Undefined Beheivor: cast between function pointer and void*.

### ISSUE THREAD

**Issue by r-kurose** [OpenRTM/OpenRTM-aist#116]
**Describe the bug**
void* (オブジェクトのポインター) を 関数ポインターに変換している｡
C++ 規格の未定義動作で､ポインターのサイズが一致するとは限らない｡
ModuleManager.cpp 167:12 

**To Reproduce**
none

**Reproducibility**
none

**Expected behavior**
C++ 規格上で定義されている妥当な方法で実装されること
上記が難しい場合､ビルド時に検出してエラーに落とすこと

**Screenshots or Logs**
none

**Environment**
 - OpenRTM-aist master 

**Additional context**
none

**Comment by r-kurose** [comment]
関数ポインタとオブジェクト関数ポインタの変換をしていることは解決されておりません。

**Comment by n-ando** [comment]
ModuleManager.cppの以下の部分と思われる。

```c++
    ModuleInitFunc init;
    init = reinterpret_cast<ModuleInitFunc>(this->symbol(name, init_func));
    init(&(Manager::instance()));

```
https://stackoverflow.com/questions/36384195/how-to-correctly-assign-a-pointer-returned-by-dlsym-into-a-variable-of-function
から、 ISO/IEC 9899:201x paper §6.3.2.3 に以下の記述有り。

> A pointer to void may be converted to or from a pointer to any object type. A pointer to any object type may be converted to a pointer to void and back again; the result shall compare equal to the original pointer.
> .
> 
> A pointer to a function of one type may be converted to a pointer to a function of another type and back again; the result shall compare equal to the original pointer. If a converted pointer is used to call a function whose type is not compatible with the pointed-to type, the behavior is undefined.

一つの解決方法として、上に記事から

### In the library
```c++
struct export_vtable {
   void (*helloworld)(void);
};
struct export_vtable exports = { func };

```

### In the caller
```c++
struct export_vtable {
   void (*helloworld)(void);
};

int main() {
   struct export_vtable* imports;
   void *handle = dlopen("./foo.so", RTLD_NOW);

   if (handle) {
        imports = dlsym(handle, "exports");
        if (imports) imports->helloworld();
    }
    return 0;
}
```

ライブラリ側の修正が必要。

別のやり方としては、
https://pubs.opengroup.org/onlinepubs/009695399/functions/dlsym.html
にある方法あり。

```c++
void    *handle;
int     *iptr, (*fptr)(int);

/* open the needed object */
handle = dlopen("/usr/home/me/libfoo.so", RTLD_LOCAL | RTLD_LAZY);

/* find the address of function and data objects */
*(void **)(&fptr) = dlsym(handle, "my_function");
iptr = (int *)dlsym(handle, "my_object");

/* invoke function, passing value of integer as a parameter */
(*fptr)(*iptr);
```

にしたがって、ModuleManager::load() 内の
```c++
    ModuleInitFunc init;
    init = reinterpret_cast<ModuleInitFunc>(this->symbol(name, init_func));
    init(&(Manager::instance()));
```
を
```c++
    void (*initfptr)(Manager*);
    // *(void **)(&initfptr) = だと古いキャストだと怒られるので以下のように変更 
    *reinterpret_cast<void**>(&initfptr) = this->symbol(name, init_func);
    (*initfptr)(&(Manager::instance()));
```

のように変更することで、コンパイラのwarning (gcc-9を使用) は出なくなった。
