### ISSUE TITLE
CMakeのオプションでexamples、extをビルドするか選択可能にする

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
CMake実行時のオプションでexamplesをビルドするか選択可能にする。
デフォルトはビルドする。
またext以下のモジュールについても選択可能にする。

**Describe alternatives you've considered**

**Additional context**

**Comment by r-kurose** [comment]
make ConsoleIn.so
make examples/install
make examples/SimpleIO/install
は自動生成されています。
後は使う側で自分に合わせたスクリプトで足りるのではないかと。
ただし、実行ファイルを作るコマンドは生成されていないようです。
おそらく set_property かなにかで設定すればできると思います。
