### ISSUE TITLE
範囲ベースのfor loopに統一する

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#199]
**Is your feature request related to a problem? Please describe.**
#160 

**Describe the solution you'd like**
範囲ベースのfor (auto& hoge: dara){}に統一する。

**Describe alternatives you've considered**

**Additional context**

**Comment by r-kurose** [comment]
@Nobu19800 
ツールでの変更は #202 で実施しました。
ツールでの変換は少なくとも2回に分けて実施します。
今回はその初回で修正しても問題なさそうな (レビューの負担が少なそうな) ものになっています。
ツールの補助はここまでとなるので、気に入らないイテレータ名を変更するなどはお願いします。

**Comment by r-kurose** [comment]
設定を強めに変更して2度目のチェックをしたところ、(期待に反して?)修正するところが見つかりませんでした。
win32 や ROS/ROS 2 コードはビルド対象になっていないので、ビルド環境が整ったときに対応します。
本 issue の残作業としては、手で直したいところがあれば、変えておく程度です。

**Comment by r-kurose** [comment]
#249
