### ISSUE TITLE
fail fluent build

### ISSUE THREAD

**Issue by r-kurose** [OpenRTM/OpenRTM-aist#263]
**Describe the bug**
Fluentbit のビルドに失敗する

**To Reproduce**
1. cmake -DFLUENTBIT_ENABLE=ON 以下略
2. make

**Reproducibility**
100%

**Expected behavior**
ビルド完了すること

**Screenshots or Logs**

```
Step 9/9 : RUN cmake -DCORBA=omniORB -DSSL_ENABLE=ON -DOBSERVER_ENABLE=ON -DFLUENTBIT_ENABLE=TRUE -DFLUENTBIT_ROOT=/usr -DFLUENTBIT_WORKDIR=/root/fluent-bit/build
-S . -Bbuild_openrtm && cmake --build build_openrtm -- -j$(nproc)
　　　：
CMake Error at src/ext/logger/fluentbit_stream/CMakeLists.txt:60 (target_include_directories):
 Cannot specify include directories for target "SYSTEM" which is not built
 by this project.
```

**Environment**
 - OS: Docker  Ubuntu 16.04
 - OpenRTM-aist master

**Additional context**
使用した Dockerfile
https://github.com/n-kawauchi/OpenRTM-aist/blob/master/build/ubuntu_1604/Dockerfile

**Comment by r-kurose** [comment]
@Nobu19800
make で失敗します。
CMakeLists.txt に記述されているものとはバージョンが不一致でヘッダが見えません。
```
~/fluent-bit/lib# ls
flb_libco  jsmn           monkey         onigmo  sqlite-amalgamation-3200000
jemalloc   mbedtls-2.5.1  msgpack-2.1.3  sha1
```

Fluent が使用するライブラリたちを正しく /usr 以下にインストールするのが正攻法にも見えます。
現状は make install しても fluent のヘッダしかインストールされていません。

**Comment by Nobu19800** [comment]
Fluent-Bit、関連するライブラリのインストール手順を以下にまとめました。

- https://tmp.openrtm.org/openrtm/ja/content/fluentbit#toc1

#278 にも書きましたが、flb_libcoというライブラリはインストールする方法がないため、Fluent-Bitのディレクトリの指定は必要です。

また、修正前でもFluent-Bit 1.0.0以上ならバージョン番号は一致するはずです。
おそらく変なところからFluent-Bitのソースコードを入手したのではないかと思います。

**Comment by r-kurose** [comment]
対応いただいた PR #278 が PR #264 を含むので取り下げておきます。

**Comment by r-kurose** [comment]
@n-kawauchi
現状の問題は解決されたので、試してみてください。
良さそうなら Issue はクローズかと思います。

**Comment by n-kawauchi** [comment]
#278 と #279 のPRをマージした環境でビルドが通りました。
Fluentbitと各種ライブラリをインストールするDockerfileは下記です。
https://github.com/n-kawauchi/OpenRTM-aist/blob/master/build/ubuntu_1604/Dockerfile
ビルド結果は下記です。
https://travis-ci.org/n-kawauchi/OpenRTM-aist/jobs/508308704

**Comment by r-kurose** [comment]
無事解決し、 master にもマージされたのでクローズします。
