### ISSUE TITLE
Ubuntuでmake installでインストールしたサンプルコンポーネントが動作しない

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#275]
**Describe the bug**
Ubuntuでmake installコマンドによりインストールした場合に、サンプルコンポーネント実行時に以下のエラーが発生する。

```
loading shared libraries: libRTC.so.2.0: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Ubuntu上でビルドする
2. make installコマンドで`/usr/local`にインストールする
3. サンプルコンポーネントを実行する
```
/usr/local/share/openrtm-2.0/components/c++/examples/ConsoleInComp 
```

**Reproducibility**
100％
**Expected behavior**

**Screenshots or Logs**

**Environment**
 - OS:  Ubuntu 18.04
 - OpenRTM-aist 2.0

**Additional context**

**Comment by r-kurose** [comment]
インストール後に ldconfig -v していないので、見えていないのではないでしょうか。
