### ISSUE TITLE
旧バージョンのパッケージの入手方法

### ISSUE THREAD

**Issue by y-masutani** [OpenRTM/OpenRTM-aist#290]
旧バージョンのパッケージはどこで入手できますか？

**Comment by n-kawauchi** [comment]
升谷先生、OpenRTM-asit 1.1.2版のWindowsインストーラをご所望でしょうか？

**Comment by y-masutani** [comment]
いえ，1.1.2のUbuntu用のパッケージを入手したいのです．
セックのAirGraphを試そうとしているのですが，新しいバージョンで動くかわかりませんので，旧バージョンを使いたいと考えています．

**Comment by n-kawauchi** [comment]
現在、aptでインストールできない状況ですので、tar.gzでまとめたものをご用意いたします。
Ubuntuのどのバージョンがよろしいでしょうか。　16.04(64bit）等を教えて下さい。

**Comment by y-masutani** [comment]
Ubuntu 16.04 64bitです．よろしくお願いいたします．

**Comment by n-kawauchi** [comment]
下記に置きました。よろしくお願いいたします。
https://github.com/OpenRTM/OpenRTM-aist/releases/download/svn%2FFRELEASE_1_1_2/OpenRTM-aist_1.1.2_ubuntu16.04_amd64_package.tar.gz

**Comment by y-masutani** [comment]
Not Found
と表示されます．

**Comment by n-kawauchi** [comment]
URL間違えました。申し訳ございません。
https://github.com/OpenRTM/OpenRTM-aist/releases/download/svn%2FRELEASE_1_1_2/OpenRTM-aist_1.1.2_ubuntu16.04_amd64_package.tar.gz

**Comment by y-masutani** [comment]
ありがとうございます．Python, Java, OpenRTPもお願いしますと書こうとしていたところで，以下に残っていることを見つけました．
https://github.com/n-ando/xenial_package
https://github.com/n-ando/openrtm-java_packages

**Comment by n-kawauchi** [comment]
お手数をおかけして申し訳ございませんでした。 
1.1.2版に関しても openrtm.orgのwebページからダウンロードできるように整える予定です。
よろしくお願いいたします。
