### ISSUE TITLE
printf の指定ミス

### ISSUE THREAD

**Issue by r-kurose** [OpenRTM/OpenRTM-aist#299]
**Describe the bug**
sprintf での型指定ミスがある

**To Reproduce**
MSVC 2013 でビルドする。オプションは最小でもOK.

**Reproducibility**
100%

**Expected behavior**
sprintf の指定を型と一致させること

**Screenshots or Logs**
https://ci.appveyor.com/project/n-kawauchi/openrtm-aist/builds/23324620/job/bkprw3lym3b58gp6
Line 270, 508

**Environment**
 -  Windows 10
 -  MVSC 2012
 - OpenRTM-aist master 9c3ba818

**Additional context**
none

**Comment by Nobu19800** [comment]
解決済みのためissueをcloseします。

**Comment by Nobu19800** [comment]
#313 でRTC_TRACEの引数に%dを指定していたのを%sに修正したため閉じました。
