### ISSUE TITLE
MSVC link-time warnings

### ISSUE THREAD

**Issue by r-kurose** [OpenRTM/OpenRTM-aist#300]
**Describe the bug**
MSVC でのリンク中に大量のワーニングが発生する。

**To Reproduce**
cmake --build でビルドする。

**Reproducibility**
100%

**Expected behavior**
リンク時の警告がないこと

**Screenshots or Logs**
https://ci.appveyor.com/project/n-kawauchi/openrtm-aist/builds/23324620/job/bkprw3lym3b58gp6
```
ModuleManager.obj : warning LNK4197: export '?m_instance@?$Singleton@V?$GlobalFactory@VNumberingPolicyBase@RTM@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@4@P6APEAV12@XZP6AXAEAPEAV12@@Z@coil@@@coil@@1PEAV?$GlobalFactory@VNumberingPolicyBase@RTM@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@4@P6APEAV12@XZP6AXAEAPEAV12@@Z@2@EA' specified multiple times; using first specification [C:\workspace\build\src\lib\rtm\RTC200_vc12.vcxproj]
```

**Environment**
 - OS: Windows 10
 - MSVC 2013/2015/2017 (2012 未確認)
 - OpenRTM-aist master 9c3ba818

**Additional context**
なし

**Comment by Nobu19800** [comment]
解決済みのためissueをcloseします。

**Comment by Nobu19800** [comment]
#309 でIDLコンパイルで生成したファイル以外のソースコードについて、モジュール定義ファイルをCMakeの機能で生成することで問題は解決したため閉じました。
