### ISSUE TITLE
Windowsでrtshellのコマンドが実行できません．

### ISSUE THREAD

**Issue by y-masutani** [OpenRTM/OpenRTM-aist#314]
Windows 10にOpenRTM-aist-1.2.0-RELEASE_x86_64.msiでインストールしました．
コマンドプロンプトで，rtshellのコマンドを実行しようとすると，以下のように表示され動作しません．
```
Fatal error in launcher: Unable to create process using '"c:\python37_x64\python.exe"  "C:\Python37\Scripts\rtpwd.exe" '
```

**Comment by y-masutani** [comment]
Python 3.2.7をC:\Python37にインストールしているのですが，このディレクトリ名をC:\python37_x64に変更し，環境変数の中の並びも変更したところ，実行できるようになりました．こうするより他ないのでしょうか？

**Comment by n-kawauchi** [comment]
ご連絡、ありがとうございます。　お手数をおかけして申し訳ございません。
rtshellのバイナリを生成し、インストーラに含めております。このバイナリ生成時の設定が影響しているということ、了解しました。

ご指摘の通りで、こちらでは32bit版PythonはC:\python37へ、64bit版はC:\python37_x64へインストールしております。

対応方法を検討いたします。しばらくお時間を頂きたく、よろしくお願いいたします。

**Comment by y-masutani** [comment]
Pythonのインストールディレクトリとは別にC:\python37_x64を作り，その中へpython.exeをコピーするだけでも大丈夫なようです．当方では，当面それでしのぐことにします．

**Comment by n-kawauchi** [comment]
rtshellをpipでインストールし直せば改善するようにいたしました。手順はwebページに「（重要なお知らせ）OpenRTM-aistインストール後の設定」として記載しました。
http://openrtm.org/#windows_packages

よろしくお願いいたします。

**Comment by y-masutani** [comment]
試してみたところ，うまくいきました．
対応ありがとうございました．

**Comment by y-masutani** [comment]
この問題への対処方法の説明が消えているようですが，Windows用のインストールパッケージを更新されましたか？

**Comment by n-kawauchi** [comment]
対処方法の説明は掲載しておりますが、上記のコメントで記載したURLでは仮運用としている従来のopenrtm.orgへ飛んでしまい、アクセスできないこと、確認しました。申し訳ございません。下記URLでアクセスできます。
https://openrtm.github.io/#windows_packages

また、openrtm.orgの方でも、1.2.0版インストーラmsi のダウンロードリンクを貼っている、C++, Python, Java の各1.2.0-RELEASEダウンロードページにも、対処方法を記載いたしました。
https://openrtm.org/openrtm/ja/content/openrtm-aist-c-120-release#toc4
https://openrtm.org/openrtm/ja/content/openrtm-aist-java-120-release#toc4
https://openrtm.org/openrtm/ja/content/openrtm-aist-python-120-release#toc4

インストーラmsiでのこの問題の対応状況ですが、現時点ではまだ対応できておりません。
お手数をおかけしております。　よろしくお願いいたします。

**Comment by y-masutani** [comment]
対応ありがとございました．
