### ISSUE TITLE
RTCのログに「Master manager not found」と繰り返し表示

### ISSUE THREAD

**Issue by y-masutani** [OpenRTM/OpenRTM-aist#318]
Windowsで1.2.0を試し始めました．RTCのログに
```
INFO: ManagerServent: Master manager not found
```
繰り返し表示されています．1.1.2の時はありませんでした．どうすればいいのでしょうか？

GitHubのIssuesに書くことではないと思いますが（ユーザ向けMLを復活させてください！），ご教示いただけると幸いです．

**Comment by Nobu19800** [comment]
そのメッセージには特に害はございません。
OpenRTM-aistのRTCを管理するマネージャにはマスターマネージャとスレーブマネージャの2種類があります。以下に説明があります。

- https://nobu19800.github.io/RTM-Lua/docs/glossary.html#%E3%83%9E%E3%83%8D%E3%83%BC%E3%82%B8%E3%83%A3

何も指定しなければスレーブマネージャとして起動するのですが、スレーブマネージャは起動時にマスターマネージャに登録を試みます。
起動時にマスターマネージャが存在しない場合は、定期的にマスターマネージャの登録を試みるため、登録失敗した場合にログにメッセージが出力されます。

マスターマネージャを使用することでRTCの動的な起動、ネームサーバーを使わずにRTCを検索するなどの機能を使えますが、マスターマネージャへの登録が失敗しても動作には影響ありません。

ログのメッセージを出力させないようにする場合は、ログレベルをWARN、ERROR等に設定するとログには表示されなくなります。

**Comment by y-masutani** [comment]
解説ありがとうございます．
1.1.2のことはこのような表示はなかったように思いますが，仕様の変更があったのでしょうか？
ログレベルINFOでコンポーネントの動作確認に必要な情報を出力するようにしていますので，ログレベルは変更したくありません．何かいい方法はないでしょうか？

**Comment by Nobu19800** [comment]
1.1.2ではマスターマネージャへ登録を試みるのは起動時だけだったため、定期的にログにメッセージは表示されませんでした。
上記のメッセージを表示させないためには、rtc.confの設定でマスターマネージャに接続する機能をOFFにする方法があります。
rtc.confに以下のように記述すると、定期的にマスターマネージャの存在確認をする機能がオフになるためメッセージはなくなります。

```
corba.update_master_manager.enable: NO
```

**Comment by y-masutani** [comment]
ありがとうございます．
やってみたところ，所望のことができました．
