### ISSUE TITLE
Windows 64bit版においてRTCビルドの際の警告

### ISSUE THREAD

**Issue by y-masutani** [OpenRTM/OpenRTM-aist#323]
Windows 64bit版において，RTC Builderで生成したソリューションをそのままビルドしても警告が多数表示されます．実害はないかもしれませんが，授業で使うことを考えると嬉しくありません．自分のコードのせいで発生したエラーや警告が紛れてしまいますので．

出ている警告は，種類としては2種類で，
```
C4996	'GetVersionExA': が古い形式として宣言されました。
```
と
```
C4267	'=': 'size_t' から 'int' に変換しました。データが失われているかもしれません。	
```
です．前者はわかりませんが，後者はInPort.hなどの該当部分で一時変数をintでなくsize_tとして宣言すれば解決するのではないかと思います．

**Comment by Nobu19800** [comment]
ご指摘のような警告についてはmasterブランチのソースコードではほぼ解決しています。
OpenRTM-aist 1.2に適用しなかったのは下手にリリース直前に変更すると問題があると考えたためであるため、警告についてはOpenRTM-aist 2.0では警告については解決する予定です。

**Comment by y-masutani** [comment]
そこは，ぜひ1.2.1でお願いします！

**Comment by Nobu19800** [comment]
動作に影響がないと考えられる部分については1.2.1にも修正を行いますが、masterブランチのソースコードについても警告の修正のために大幅な変更が加わっているため1.2に全て反映させるのは難しいです。
Visual Studioはファイルごとに警告を表示させることができますので、当面はこの方法で対処をお願いいたします。
