### ISSUE TITLE
Abnormal termination when RTM_ROOT does not exist.

### ISSUE THREAD

**Issue by r-kurose** [OpenRTM/OpenRTM-aist#327]
**Describe the bug**
Windows で 環境変数 RTM_ROOT がからのとき、異常終了する。

**To Reproduce**
1. RTM をビルドする。
2. RTM_ROOT をセットしない または set RTM_ROOT=
3. 例えば ConsoleInComp を起動する

**Reproducibility**
100%

**Expected behavior**
デフォルト設定のロードがされて、コンポーネントが動作すること。

**Screenshots or Logs**
ログもなく終了する。

**Environment**
 - OS: Windows 10
 - OpenRTM-aist Version master 4013f2e
 - MSVC 2017

**Additional context**
none

**Comment by n-kawauchi** [comment]
WindowsでのOpenRTM-aistに関するシステム環境変数は、インストーラmsiが設定します。
msiを使わずに環境を構築することは想定していないとの認識です。
cmakeでインストールした場合もシステム環境変数の設定が必要ということでしょうか？

**Comment by r-kurose** [comment]
本件は、本来の仕様であろう「rtc.confg がない場合はシステムのデフォルト設定で動く」ということが、
正しく実装されていないというバグです。

cmake での環境変数設定は不要です。
インストーラで設定されているのでこの現象を踏む人が少なかったということです。

**Comment by Nobu19800** [comment]
解決済みのためissueをcloseします。

**Comment by Nobu19800** [comment]
この問題は環境変数を取得するcoil::getenv関数がnullptrを返す場合にnullptrかどうかの判定をしていなかったことが問題のため、#331 で環境変数を取得できた場合はtrue、できなかった場合はfalseを返すように変更、該当箇所を修正した。このためissueを閉じました。
