### ISSUE TITLE
ログファイルのエスケープシーケンス

### ISSUE THREAD

**Issue by y-masutani** [OpenRTM/OpenRTM-aist#330]
リリースノートによると「ログファイルのエスケープシーケンスをデフォルトで無効にする機能」とのこですが，エスケープシーケンスを有効にするにはどうすればいいのでしょうか？

というような，リリースノートに関する詳細はどこを見ればいいでしょうか？

**Comment by Nobu19800** [comment]
ログのエスケープシケーンスはrtc.confに以下のように記述すると有効になります。

```
logger.escape_sequence_enable: YES
```

また新機能の詳細については以下のページに記載しました。

- http://openrtm.org/openrtm12.html

**Comment by y-masutani** [comment]
ありがとうございます．教えていただいた方法でロガーのエスケープシーケンスを有効にすることができました．端末に表示させている場合は，色の違いがある方がわかりやすいですね．出力先によって，エスケープシーケンスの有効・無効が自動的に切り替わると便利だと思います．

それから，新機能の詳細についてもありがとうございます．少しずつ確認していきます．
