### ISSUE TITLE
DLL名にアーキテクチャ名を含める

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#339]
**Is your feature request related to a problem? Please describe.**
1.2.0以前では64bitの場合にDLL名に_x64がついていたが、masterブランチのソースコードをビルドしても付かなくなっている。
ARMは考慮していない。

**Describe the solution you'd like**
`CMAKE_GENERATOR_PLATFORM`の値で判別してアーキテクチャ名を付けるようにする。

- RTC200_vc142_x64.dll

- RTC200_vc142_Win32.dll

- RTC200_vc142_ARM.dll

- RTC200_vc142_ARM64.dll

**Describe alternatives you've considered**

**Additional context**

**Comment by r-kurose** [comment]
参考:
https://cmake.org/cmake/help/v3.12/variable/CMAKE_GENERATOR_PLATFORM.html
