### ISSUE TITLE
rtshellやrtctreeで共有メモリ通信データポート

### ISSUE THREAD

**Issue by y-masutani** [OpenRTM/OpenRTM-aist#348]
rtshellやrtctreeで「共有メモリ通信データポート」を利用するにはどのようにすればいいのか教えてください．

**Comment by Nobu19800** [comment]
rtshell、rtctreeにはコネクタ接続時にプロパティを設定する機能を使用すれば利用できます。

rtshellのrtconコマンドを使用する場合、以下のように--property(もしくは-p)の後に設定を入力します。

```
rtcon /localhost/ConsoleIn0.rtc:out /localhost/ConsoleOut0.rtc:in --property dataport.interface_type=shared_memory
```

rtctreeで接続する場合は以下のように引数の`props`で設定します。

```Python
outport.connect([inport], props={"dataport.interface_type":"shared_memory"})
```

**Comment by y-masutani** [comment]
ご教示いただきありがとうございます．応答が遅くなり申し訳ありません．
教えていただいたプロパティを指定することにより，接続のinterface typeがshared memoryに切り替わっていることが確認できました．
