### ISSUE TITLE
FluentBitのビルドで Warning がでる

### ISSUE THREAD

**Issue by tonboAkinori** [OpenRTM/OpenRTM-aist#359]
**Describe the bug**
FluentBitのビルドで失敗する、下記のTravisCI のログを参照。
https://travis-ci.org/OpenRTM/OpenRTM-aist/jobs/518668968

■下記が関係している
- 先週から Travis CI で Ubuntu 18.04 + Fluent のビルドが開始された
- #358 の対応で DEBUG_TYPE=Releaseを有効かされる
- #358 の対応で警告はエラーと扱われる

■気になること
- flb_libco のヘッダがなくてもビルドが通っていたように見える

**To Reproduce**
1.  build/ubuntu_1804/Dockerfileでイメージビルドする

**Reproducibility**
Ran 1 times, occurred 1 times.

**Expected behavior**
ビルドが成功する

**Screenshots or Logs**

**Environment**
 - OS: Ubunt 18.04 on Docker 
 - OpenRTM-aist Version 2.0

**Additional context**

**Comment by r-kurose** [comment]
現在の libco の場所は下記の通り。
https://github.com/OpenRTM/OpenRTM-aist/blob/master/build/ubuntu_1804/Dockerfile_devel-rtm

**Comment by Nobu19800** [comment]
libco.hの場所ですが、多分意図と違う場所にコピーしています。
`/usr/local/include/libco.h`にコピーされるようですが、`${FLUENTBIT_ROOT}/lib/flb_libco/libco.h`に配置する必要があるため、`FLUENTBIT_ROOT`を`/usr/local/include`に指定した場合は`/usr/local/include/lib/flb_libco/libco.h`が正しいという事になります。

**Comment by Nobu19800** [comment]
解決済みのためissueをcloseします。

**Comment by Nobu19800** [comment]
#363 で警告の修正を行ったため閉じました。
