### ISSUE TITLE
モジュールのロードなどに時間がかかるとManagerがコンポーネント起動前に終了する

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#380]
**Describe the bug**
`manager.shutdown_auto`を有効にした場合、Managerの初期化からコンポーネント起動までに時間がかかると勝手にManagerが終了しようとすることがある。

**To Reproduce**
1. Init関数の実行に20秒程度かかるdllを用意する
2. rtc.confで上記のdllをロードするように設定する。
3. ConsoleInComp.exe等を実行する。
4. 以下のように表示されRTCは起動しない。

```
omniORB: (0) 2019-04-19 11:12:38.122000: Error: the application attempted to invoke an operation on a nil pseudo-object reference.
```

**Reproducibility**
100％

**Expected behavior**

**Screenshots or Logs**

**Environment**
 - OS:  Windows 10
 - OpenRTM-aist 2.0

**Additional context**

**Comment by n-ando** [comment]
-o "manager.auto_shutdown_duration:30" のようにすれば変更できるので、ロードに時間がかかる場合はオプションで対処可能。そもそも、初期化に何十秒もかかるDLLは作り的によろしくない。

とりあえず、durationはデフォルトで10sだったが、WindowsなどではManagerの初期化、DLLのロードに時間がかかりがちなので、もう少し余裕をみて20sとした。
