### ISSUE TITLE
コンポーネント起動時のメッセージと標準ログ機能の干渉

### ISSUE THREAD

**Issue by y-masutani** [OpenRTM/OpenRTM-aist#383]
バージョン1.2ではコンポーネントの起動時に色々と情報が表示されるようになりました．それはそれで有用だと思うのですが，標準ログ機能の出力先を標準出力に設定していると（`logger.file_name: stdout`），二つの出力が混ざって表示が乱れ，内容が読み取れなくなります．行単位で混ざるのならばまだいいのですが，文字単位で混ざっています．これを回避することはできないでしょうか？

Windowsで使っています．

**Comment by Nobu19800** [comment]
現状では回避する方法はありません。修正版では表示自体がなくなる予定です。
予定よりも早く修正版を出せるように作業しておりますので、しばらくお待ちください。

**Comment by y-masutani** [comment]
了解しました．修正版を待ちます．
