### ISSUE TITLE
_REENTRANTの再定義される問題

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#411]
**Describe the bug**

- https://openrtm.org/openrtm/ja/node/6587

**To Reproduce**
上記のURL参照。

**Reproducibility**
100％

**Expected behavior**

**Screenshots or Logs**

**Environment**
- OpenRTM-aist 1.2
masterは修正済み。

**Additional context**

**Comment by Nobu19800** [comment]
このissueはどのプルリクエストで解決したのでしょうか？

**Comment by Nobu19800** [comment]
確認したところ問題が解決していなかったためReopenします。

**Comment by r-kurose** [comment]
その昔に Solaris で使われていたフラグに見えますが、当時必要だったことがあるのでしょうか。
https://docs.oracle.com/cd/E19455-01/806-7118/compile-4/index.html
