### ISSUE TITLE
CMakeによるビルドが通らない

### ISSUE THREAD

**Issue by kazuki0824** [OpenRTM/OpenRTM-aist#421]
**Describe the bug**
ファイルのパスが間違っているので、そのままではビルドが通らない。

**To Reproduce**
1. カレントディレクトリをopenrtm-aistにする
2. cmake .
3. make

**Reproducibility**
毎回

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment**
 - OS:  Ubuntu 18.04 64bits
 - OpenRTM-aist Version 2.0.0

**Comment by Nobu19800** [comment]
現状、は以下に記載してあるようにファイルを移動させる必要があります。

- https://openrtm.org/openrtm/ja/content/cmake_build_rtm


1.2以前ではビルド時にファイルのコピーを行っており、最初から適切な場所にファイルを配置しておけばこの作業は必要ないのですが、そもそも1.2以前のautomakeによるビルドシステムを残すのか捨てるのかについて結論が出ていないのでそのままにしてあります。
