### ISSUE TITLE
CMakeでインストールすると、pkgconfigのcflagsが空になってしまう

### ISSUE THREAD

**Issue by kazuki0824** [OpenRTM/OpenRTM-aist#423]
**Describe the bug**
CMakeで使用するopenrtm-aist-cmake.pc.inが不適切なため、CMakeからインストールするとopenrtm-aistのcflagsが空白になってしまう

**To Reproduce**
Ubuntu 18.04において
1. cmakeからインストール(CMAKE_INSTALL_PREFIX=/usr)
2. pkg-config openrtm-aist --cflags
3. 改行文字のみが出力される。

**Reproducibility**
Every

**Expected behavior**
-I/usr/include/openrtm-2.0 ....と続く

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment**
 - OS: Ubuntu 18.04
 - OpenRTM-aist Version 2.0

**Comment by Nobu19800** [comment]
pkgconfigについては、1.2.0以前のビルドシステムでopenrtm-aist.pc生成していたので2.0のビルドシステムでもとりあえず生成するようにしましたが、OpenRTMConfig.cmakeでCMakeで使えたら十分だと考えてopenrtm-aist.pcを廃止するかを検討中です。開発人数の関係でpkgconfigまでサポートするのは無理があるからです。

**Comment by n-ando** [comment]
pkgconfigはLinux上でライブラリをリンクする標準的な方法なのでそのまま更新。
