### ISSUE TITLE
ビルド時にyat.pyをコピーしないようにする

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#429]
**Is your feature request related to a problem? Please describe.**
現状、ビルドする際にyat.pyをrtm-skelwrapperフォルダにコピーしている。

**Describe the solution you'd like**
yat.pyをコピーしないようにしたい。

**Describe alternatives you've considered**
以下の2つの方法が考えられる。

- yat.pyを配置しているフォルダ(build)をrtm-skelwrapper実行時にimportの対象パスに設定する。
- 最初からrtm-skelwrapperフォルダにyat.pyを配置する

rtm-skelwapper以外にyat.pyを使用するスクリプトをすべて廃止する場合はrtm-skelwapperフォルダに移動させてほしい。
そうでない場合はパスを設定する方法をとる。

**Additional context**

**Comment by r-kurose** [comment]
閉じた理由は何でしょうか。

**Comment by Nobu19800** [comment]
yat.pyをrtm-skelwrapperに移動させており、ビルドの前にyat.pyをコピーする必要は無くなっているので解決済みのはずです。
