### ISSUE TITLE
RTCを起動するバッチファイル、confファイルの整理

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#432]
**Is your feature request related to a problem? Please describe.**
msiインストーラーでインストールした場合のRTCを起動するバッチファイル、confファイルは以下の点について修正すべき。

- SimpleIOのrtc.confがインストールされる。ほとんどのRTCでSimpleIOのrtc.confを使用するようになっている。
- rtm_env.batが環境変数の設定だけではなくディレクトリの移動も行う
- Visual Studioのバージョンごとに同じconfファイルが複数インストールされる

**Describe the solution you'd like**
- SimpleIOのrtc.confがインストールされる。ほとんどのRTCでSimpleIOのrtc.confを使用するようになっている。

全体で使用するrtc.confなのであれば、SimpleIOではなく別フォルダに分離すべき。

- rtm_env.batが環境変数の設定だけではなくディレクトリの移動も行う

RTCを起動するバッチファイル内で以下のように`%RTM_VC_VERSION%`以下の実行ファイルを起動するように変更するべき。

```
@call rtm_env.bat
%RTM_VC_VERSION%\%~n0Comp.exe -f rtc.conf
```

- Visual Studioのバージョンごとに同じconfファイルが複数インストールされる

同一のファイルであれば1つだけインストールされるようにして、RTC実行時に`-f`オプションで指定するべき。

**Describe alternatives you've considered**

**Additional context**

**Comment by n-kawauchi** [comment]
- この修正は、subversionで管理している下記ソースの r60 にて対応済みです
https://openrtm.org/svn/openrtm-msm-buildtool/trunk/openrtm_msm/
- 修正詳細は、下記チケットに記載していますので、このIssueはcloseします
https://openrtm.org/redmine/issues/4780
