### ISSUE TITLE
examples/Templates/ と src/lib/rtm/idl/device_interfaces の整理

### ISSUE THREAD

**Issue by r-kurose** [OpenRTM/OpenRTM-aist#450]
**Is your feature request related to a problem? Please describe.**
#430 の疑問に関して話した結果、下記は同じものを対象にする xml と idl だった。
 examples/Templates/ と src/lib/rtm/idl/device_interfaces
example にあるが OpenRTM-aist のサンプルコンポーネントでもないし、
src/lib/rtm にあるが OpenRTM-aist のビルドに関係ない。

**Describe the solution you'd like**
C++ リポジトリには不要なものなので消す。
サンプルは RT System Builder に持たせるのが妥当か？

**Describe alternatives you've considered**
なし

**Additional context**
なし

**Comment by n-kawauchi** [comment]
idl/device_interfaces について補足させて下さい。
このidlファイルは、元々はOpenRTM-aist-Javaのソースに入っていました。

1.1.2版のWindows用インストーラからC++, Python, Java, ツール等を１つのmsiにまとめる仕様となりました。この時、idlファイルだけのマージモジュールをC++で作成することになり、idl/device_interfaces を加えた次第です。

現在msiでインストールする際、カスタムセットアップにて C++ を選択せず、Python、Java、OpenRTP等を単独選択された場合でも、IDLのマージモジュールと依存関係を持たせることで、下記ファイルが一緒にインストールされる仕様になっております。
```
└─rtm
    └─idl
        │  BasicDataType.idl
        │  CameraCommonInterface.idl
        │  ComponentObserver.idl
        │  DataPort.idl
        │  ExtendedDataTypes.idl
        │  InterfaceDataTypes.idl
        │  Manager.idl
        │  ManipulatorCommonInterface_Common.idl
        │  ManipulatorCommonInterface_DataTypes.idl
        │  ManipulatorCommonInterface_Middle.idl
        │  OpenRTM.idl
        │  RTC.idl
        │  SDOPackage.idl
        │  SharedMemory.idl
        │
        └─device_interfaces
                ActArray.idl
                AIO.idl
                Bumper.idl
                Camera.idl
                DIO.idl
                Fiducial.idl
                GPS.idl
                Gripper.idl
                IMU.idl
                INS.idl
                Limb.idl
                Map.idl
                Multicamera.idl
                PanTilt.idl
                Paths.idl
                PointCloud.idl
                Position.idl
                Ranger.idl
                RFID.idl
```

**Comment by n-kawauchi** [comment]
examples/Templates はこのまま残すことになったので、closeする。
