### ISSUE TITLE
StaticFSMのサンプルの***_specの修正

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#494]
**Describe the bug**
StaticFSMのサンプルMicrowaveを使用を定義した`***_spec`が以下のように`consoleout_spec`となっており、descriptionがConsoleInの説明になっている。

```CPP
static const char* consoleout_spec[] =
  {
    "implementation_id", "Microwave",
    "type_name",         "Microwave",
    "description",       "Console output component",
    "version",           "1.0",
    "vendor",            "Noriaki Ando, AIST",
    "category",          "example",
    "activity_type",     "DataFlowComponent",
    "max_instance",      "10",
    "language",          "C++",
    "lang_type",         "compile",
    ""
  };
```

Python版も同様に間違っている。Java版は未確認。

**To Reproduce**

**Reproducibility**

**Expected behavior**
サンプルコンポーネントで説明が間違っているものはすべて修正する。

**Screenshots or Logs**

**Environment**

**Additional context**

**Comment by n-ando** [comment]
PR #630 作成

**Comment by Nobu19800** [comment]
#630 で解決したようなのでCloseします。
