### ISSUE TITLE
Windowsでビルドする時にCMakeが古いとビルドできない

### ISSUE THREAD

**Issue by tonboAkinori** [OpenRTM/OpenRTM-aist#525]
**Is your feature request related to a problem? Please describe.**

Windowsで古いCMake(3.5.2)を使いビルドしようとすると
**VERSION_GREATER_EQUAL** が認識出来なくて失敗する。

WindowsのビルドはOpenRTM-aistの下記を参照した。
- OpenRTM-aist(C++版)のCMakeによるビルド手順

**Describe the solution you'd like**

今後も VERSION_GREATER_EQUAL を使うのであれば、
cmake_minimum_required (VERSION 3.0.2) を変更してほしい。

**Describe alternatives you've considered**
特になし

**Additional context**
特になし

**Comment by r-kurose** [comment]
Windows は Visual Studio 2019 の関係もあって、新しいバージョン (3.14.4以降） が前提になっています。
怪しい CMakeLists.txt になりますが、 if 文で Windows 限定であれば、
古い cmake を利用する Linux 環境にも影響がありません。

**Comment by tonboAkinori** [comment]
コメント、また #664 により指摘した表現が削除されているので本 Issue はクローズします。
