### ISSUE TITLE
display `rtm-config: not found` on make

### ISSUE THREAD

**Issue by r-kurose** [OpenRTM/OpenRTM-aist#61]
**Describe the bug**
ビルド中にコマンドが見つからないというログがでる｡
`sh: 1: rtm-config: not found`
ただし､ビルド手順に yat.py を手動でコピーするという
ワークアラウンドが入っているためにビルドは完了する｡

**To Reproduce**
1. cmake
2. make
問題のログは make 時のエラー出力にでるため､
標準出力を捨てるか､ファイルに書き出すと見やすい｡
make > build.log

**Reproducibility**
100%

**Expected behavior**
not found が表示さず､ワークアラウンドなしでビルドが通ること｡

**Screenshots or Logs**
none

**Environment**
 - OS: Ubuntu 16.04, 18.04
 - OpenRTM-aist Version master b50148a6459561d34297bf45fc9d58dcd8a6e7a8 など

**Additional context**
 Dockerfile もワークアラウンド (シンボリック) が入っているので､
 この修正完了時に合わせて修正するべき｡

**Comment by n-kawauchi** [comment]
現時点のmasterの最新ソース bd21c8e を使うと、Ubuntu16.04でも18.04でもログに出ていません。
ログをファイルに書き出して検索しましたが、「rtm-config」見つかりませんでした。

**Comment by r-kurose** [comment]
OpenRTM が既にインストールされている環境ではでてこないそうです｡
そういう環境でチェックされましたか?

**Comment by n-kawauchi** [comment]
すみません、OpenRTM 1.2.0版がインストールされている環境での確認でした。
