### ISSUE TITLE
OutPortBase がプロパティを使用時に書き換えるのは意図したものかものか

### ISSUE THREAD

**Issue by r-kurose** [OpenRTM/OpenRTM-aist#611]
#605 対応時の疑問： 以下だけ参照で受けていて、プロパティそのものを書き換えているが意図したものか
https://github.com/OpenRTM/OpenRTM-aist/blob/3fcb3494b87f583f85b59786d42836e936a86ced/src/lib/rtm/OutPortBase.cpp#L628-L629

他の3箇所はプロパティに対する副作用が無い。
https://github.com/OpenRTM/OpenRTM-aist/blob/3fcb3494b87f583f85b59786d42836e936a86ced/src/lib/rtm/OutPortBase.cpp#L549-L550
https://github.com/OpenRTM/OpenRTM-aist/blob/3fcb3494b87f583f85b59786d42836e936a86ced/src/lib/rtm/InPortBase.cpp#L511-L512
https://github.com/OpenRTM/OpenRTM-aist/blob/3fcb3494b87f583f85b59786d42836e936a86ced/src/lib/rtm/InPortBase.cpp#L592-L593

**Comment by n-ando** [comment]
[pP][uU][sS][hH], [pP][uU][lL][lL] の指定を受け入れるために、一旦全部小文字にして比較してます。

**Comment by Nobu19800** [comment]
多分、なぜ`OutPortBase`の`subscribeInterfaces`関数でのみプロパティを書き換えていて、他の似たような箇所(`OutPortBase`の`publishInterfaces`関数等)では書き換えないようにしているのかという質問だと思います。

**Comment by n-ando** [comment]
ここは書き換えより、文字列比較の段階で大文字小文字を区別しないようにするべきでしたね。

**Comment by n-ando** [comment]
参照&は削除してください。

**Comment by n-ando** [comment]
#661 にて修正
