### ISSUE TITLE
LocalServiceAdmin における mutex の使用がバグに見える

### ISSUE THREAD

**Issue by r-kurose** [OpenRTM/OpenRTM-aist#616]
下記で m_mutex を使っているがこれは coil::Singoleton で定義されたもののに見える。
意図したものか、そうでないなら何が正しいのか。
https://github.com/OpenRTM/OpenRTM-aist/blob/7ea713b2b06e20fe86ae4ae8b9a1e91366eb665d/src/lib/rtm/LocalServiceAdmin.cpp#L273-L276

**Comment by n-ando** [comment]
バグです。正しくは m_services_mutex でガードすべきです。

**Comment by n-ando** [comment]
#660 にて修正。
