### ISSUE TITLE
WindowsでCMake実行後に生成したINSTALLのプロジェクトのビルド時にファイルをコピーするディレクトリがおかしくなる

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#663]
**Describe the bug**

- https://openrtm.org/redmine/issues/4482

Visual StudioでINSTALLのプロジェクトをビルドすると以下のように、「1.2.1Components」というディレクトリに実行ファイルがコピーされてしまう。

```
  -- Installing: C:/Program Files/OpenRTM-aist/1.2.1Components/c++/Category/test5/test5/test5.lib
  -- Installing: C:/Program Files/OpenRTM-aist/1.2.1Components/c++/Category/test5/test5/test5.dll
  -- Installing: C:/Program Files/OpenRTM-aist/1.2.1Components/c++/Category/test5/test5/test5Comp.exe
  -- Installing: C:/Program Files/OpenRTM-aist/1.2.1Components/c++/Category/test5/test5/RTC.xml
```

**To Reproduce**
1. Visual StudioでRTCをビルドする
2. Visual StudioのINSTALLのプロジェクトをビルドする

もしくはcmake-guiで確認できる。

**Reproducibility**
100％

**Expected behavior**
OpenRTMConfig.cmakeかRTC Builderの出力するコードのどちらが間違っているのか不明のため調査する。

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist 1.2.1

**Additional context**

**Comment by n-kawauchi** [comment]
この件の修正について、相談させて下さい。

ご指摘の不具合はソースコードからインストールする際の不具合で、これはテンプレートの1か所にスラッシュを追加すれば改善することは確認しました。　しかし、アンインストール（「プロジェクト名_uninstall」プロジェクトをビルド）が動きません。

このアンインストール時に削除するファイルのリストは、cmake実行時にinstall_manifest.txtとして生成されます。このリストのパスが実際と異なるので削除できない状況です。
下記の例では、パスに「ImageCalibration」が二重にあったり、インストールしていないbinディレクトリが含まれています。

install_manifest.txt例
```
C:/Program Files/OpenRTM-aist/1.2.1/Components/c++/Category/ImageCalibration/bin/msvcp140.dll
C:/Program Files/OpenRTM-aist/1.2.1/Components/c++/Category/ImageCalibration/bin/vcruntime140.dll
C:/Program Files/OpenRTM-aist/1.2.1/Components/c++/Category/ImageCalibration/bin/concrt140.dll
C:/Program Files/OpenRTM-aist/1.2.1/Components/c++/Category/ImageCalibration/ImageCalibration/ImageCalibration.lib
C:/Program Files/OpenRTM-aist/1.2.1/Components/c++/Category/ImageCalibration/ImageCalibration/ImageCalibration.dll
C:/Program Files/OpenRTM-aist/1.2.1/Components/c++/Category/ImageCalibration/ImageCalibration/ImageCalibrationComp.exe
C:/Program Files/OpenRTM-aist/1.2.1/Components/c++/Category/ImageCalibration/ImageCalibration/RTC.xml
```

CPackによりWindows環境ではmsiを生成可能として整えています。msiを使ってインストールすれば、コントロールパネルからアンインストールできます。
さらにソースコードからのインストールもサポートするとなると、CMakeLists.txtの修正が大きくなり、現時点で修正の見通しが立っておりません。

少なくとも1.2.1のマイルストーンからは外してもよいと思えるのですが、いかがでしょうか。

**Comment by n-kawauchi** [comment]
この件、1.2.1での対応は見送ること了承して頂きましたので、マイルストーンを変更しました。

**Comment by n-kawauchi** [comment]
PR422で対応済みですのでCloseします。
