### ISSUE TITLE
shutdown関数とfinalize関数の違いが不明

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#668]
RTObject_implクラスにshutdown関数とfinalize関数が定義されているが違いが分からない。
finalize関数は実質shutdown関数を呼ぶだけのため存在意義が不明。

**Comment by n-ando** [comment]
- RTObject_impl::exit()
  - CORBAオペレーション、ミドルウェア（マネージャ）から呼び出されることを想定
  - 主な仕事: deactivation と EC(owned)の停止、EC(other)からの切り離し、finalize()の呼び出し

> 5.2.2.2.4 exit
> **Description**
> Stop the RTC’s execution context(s) and finalize it along with its contents.
> **Semantics**
> Any execution contexts for which the RTC is the owner shall be stopped.
> If the RTC participates in any execution contexts belonging to another RTC that contains it, directly or indirectly (i.e., the
> containing RTC is the owner of the ExecutionContext), it shall be deactivated in those contexts.
> After the RTC is no longer Active in any Running execution context, it and any RTCs contained transitively within it
> shall be finalized.
> **Constraints**
> - An RTC cannot be exited if it has not yet been initialized. Any attempt to exit an RTC that is in the Created state shall fail with ReturnCode_t::PRECONDITION_NOT_MET.

- RTObject_impl::finalize()
  - CORBAオペレーション、ミドルウェア（マネージャ）から呼び出されることを想定
  - 主な仕事: このRTCの完了を行い、デストラクトの準備を行う (OMG仕様書より)
    - on_finalize() を呼び出す (OMGの仕様書より)
    - RTCの終了処理を行う -> shutdown() 呼び出し

> 5.2.2.2.2 finalize
> **Description**
> Finalize the RTC that realizes this interface, preparing it for destruction.
> **Semantics**
> This invocation of this operation shall result in the invocation of the callback ComponentAction::on_finalize.
> **Constraints**
> - An RTC may not be finalized while it is participating in any execution context. It must first be removed with ExecutionContextOperations::remove_component. Otherwise, this operation shall fail with
> - ReturnCode_t::PRECONDITION_NOT_MET. See Figure 5.10 .
> - An RTC may not be finalized while it is in the Created state. Any attempt to invoke this operation while in that state shall fail with ReturnCode_t::PRECONDITION_NOT_MET.
> - Application developers are not expected to call this operation directly; it exists for use by the RTC infrastructure.

- RTObject_impl::shutdown() 
  - 実装のための関数(RTCの仕様にはない)
  - 主な仕事: RTCのデストラクトのための準備を行う 
    - port, ec, その他リソースの終了処理、削除、切り離し等
    - shutdown()自体は本来 protected でも良い関数

**Comment by Nobu19800** [comment]
それだとexit関数やinitialize関数には実装のための関数がないので、finalize関数にも実装のためのshutdown関数は必要ないという事にはならないのでしょうか？

**Comment by n-ando** [comment]
単なる関数分割の問題です。
exitとinitializeはそれほどすることがないので。

**Comment by Nobu19800** [comment]
#923 のissueを新たに作成したのでcloseします。
