### ISSUE TITLE
コメントアウトされた制御文の是正

### ISSUE THREAD

**Issue by r-kurose** [OpenRTM/OpenRTM-aist#678]
**Is your feature request related to a problem? Please describe.**
下記の部分がコメントアウトで残されている理由がわからない。
https://github.com/OpenRTM/OpenRTM-aist/blob/5fcca4a0d906b72429c646d85f749b17092eea09/src/lib/rtm/OutPortConnector.h#L274

**Describe the solution you'd like**
残している理由をコメントする。

**Describe alternatives you've considered**
コードを消す。

**Additional context**
-

**Comment by n-ando** [comment]
@Nobu19800 不要ならコメント削除してください。

**Comment by Nobu19800** [comment]
既に削除済みです。
