### ISSUE TITLE
ObjectManager がグローバル定義なのはなぜか

### ISSUE THREAD

**Issue by r-kurose** [OpenRTM/OpenRTM-aist#679]
ObjectManager はどの名前空間にも属していない。
意図的にそうしているのか、修正が必要なのか。

**Comment by n-ando** [comment]
ObjectManagerは汎用的なクラステンプレートとして作ったので、namespace RTCに入れるのもそぐわないためグローバルになっています。このクラスをはおそらくcoilはなかったのでしょう。今ならcoilのcommonにでも入れておいた方が良いと思います。

**Comment by r-kurose** [comment]
修正用 issue 発行につき終了
