### ISSUE TITLE
Windowsソースからのビルドで問題あり。

### ISSUE THREAD

**Issue by kkunita-work** [OpenRTM/OpenRTM-aist#692]
**Describe the bug**
* Visual Studio 2019への対応ができていない
* Python 3.7(多分3.6も)でエラーが起こる
* 修正量は結構ありそうだし検証もある程度時間がかかるかも
* 現状Build.batがまったくVS 2019に対応ができていない。Python 3.xは使用しているPythonプログラム側に問題がありそう。

**To Reproduce**
C++版1.2系のソースからのビルド(Windows編)のWebページの記述にあわせてBuildを、Visual Studio 2019、Python 3.7の環境でBuild.batを実行するとエラーが起こる

**Reproducibility**
簡単にいつでも発生。

**Expected behavior**
エラーが発生

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment**
 - OS: [e.g. Ubuntu 16.04 32bits]
 - OpenRTM-aist Version [e.g. 1.2.1]
 - ...

**Additional context**

**Comment by n-ando** [comment]
msi 作成には現在 VS2015を使用している。Visual Studio 2019でのビルドは、未着手だが、一般ユーザには関係ないので、リリースには影響なし。
