### ISSUE TITLE
WindowsとUbuntuでext以下のIDLファイルのインストール先が異なる理由

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#701]
ext以下のIDLファイル(`ManipulatorCommonInterface_Common.idl`、`ManipulatorCommonInterface_DataTypes.idl`、`ManipulatorCommonInterface_Middle.idl`、`CameraCommonInterface.idl`)のインストール先が以下のようになっている。

- Windows：(`C:\Program Files\OpenRTM-aist\1.2.1\rtm\idl`)
- Ubuntu：(`/usr/include/openrtm-1.2/rtm/ext`)

WindowsではBasicDataType.idl等と同じidlフォルダにインストールして、Ubuntuではidlとは別のextにインストールするのはなぜでしょうか？

インストールするパスが違うのでRTCBuilderで`ManipulatorCommonInterface_Common.idl`等で定義したインターフェースが表示されない問題が発生しています。

**Comment by n-kawauchi** [comment]
これは、#566 の修正の際に対応しています。下記の2か所にインストールされます。
```
/usr/share/openrtm-1.2/idl/ManipulatorCommonInterface_Middle.idl
/usr/share/openrtm-1.2/idl/ManipulatorCommonInterface_Common.idl
/usr/share/openrtm-1.2/idl/CameraCommonInterface.idl
/usr/share/openrtm-1.2/idl/ManipulatorCommonInterface_DataTypes.idl

/usr/include/openrtm-1.2/rtm/idl/ManipulatorCommonInterface_Middle.idl
/usr/include/openrtm-1.2/rtm/idl/ManipulatorCommonInterface_Common.idl
/usr/include/openrtm-1.2/rtm/idl/CameraCommonInterface.idl
/usr/include/openrtm-1.2/rtm/idl/ManipulatorCommonInterface_DataTypes.idl
```

**Comment by Nobu19800** [comment]
対応済みだったのは知りませんでした。このissueは閉じます。
