### ISSUE TITLE
Warning at Composite Sample Component Execution

### ISSUE THREAD

**Issue by kkunita-work** [OpenRTM/OpenRTM-aist#734]
**Describe the bug**
サンプルコンポーネント Composite.batを実行すると、以下のメッセージがコンソールに表示される。メッセージそのものはWarningというよりはエラーメッセージに近いが、ちゃんと動作はしているようです。ただ正常動作がどういうものかの仕様が分からないので、なんとも言えないところです。

setOnSetConfigurationSet function is obsolete.
Use addConfigurationSetListener instead.
setOnAddConfigurationSet function is obsolete.
Use addConfigurationSetListener instead.

**Reproducibility**
Componennt.batを実行すれば良い

**Expected behavior**
これは良く分からないですが、たぶんComposite Componenntsの接続にそって、Sensor In/Out, Motor In/Out Controller In/Outの値を表示するのかなと思います。

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment**
 - OS:Windows 10
 - OpenRTM-aist Version 1.2.1
 - ...

**Additional context**

**Comment by n-ando** [comment]
PR #911 にて修正。
