### ISSUE TITLE
configure.acへRaspbian Buster用ライブラリのパスを追加する

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTM-aist#735]
**Is your feature request related to a problem? Please describe.**
- Raspbian Buster環境でOpenRTM-aistのdebパッケージを作成しようとすると、configureでlibomniORB4.soを見つけることができない。
```
$ ./configure --prefix=/usr --enable-fluentd=yes --enable-observer=yes --enable-ssl=yes
   :
checking for libomniORB4.so... not found
configure: error: use --with-omniorb to locate libomniORB4.so
```
- Raspbian Buster環境にlibomniORB4.soはインストールされている
```
$ sudo find / -name "*omniORB4*so"
/usr/lib/arm-linux-gnueabihf/libomniORB4.so
```

**Describe the solution you'd like**
- configure.acのbase_libsへ /usr/lib/arm-linux-gnueabihf を追加する

**Describe alternatives you've considered**
- エラーメッセージの「--with-omniorb」オプションで指定しても反映されなかったので、base_libsへパスを追加することで対応する
```
$ ./configure --prefix=/usr --with-omniorb=/usr/lib/arm-linux-gnueabihf --enable-fluentd=yes --enable-observer=yes --enable-ssl=yes
  :
checking for libomniORB4.so... not found
configure: error: use --with-omniorb to locate libomniORB4.so
```

**Comment by r-kurose** [comment]
configure の環境変数設定では駄目ですか。
 LD_LIBRARY_PATH

**Comment by n-kawauchi** [comment]
ありがとうございます。LD_LIBRARY_PATHの指定でconfigureが通りました。
```
$ export LD_LIBRARY_PATH=/usr/lib/arm-linux-gnueabihf
$ ./configure --prefix=/usr --enable-fluentd=yes --enable-observer=yes --enable-ssl=yes
    :
checking for libomniORB4.so... found in /usr/lib/arm-linux-gnueabihf
```
このIssueは閉じます。
