### ISSUE TITLE
std::chrono::nanosecondsの変数が不定値の場合がある

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#780]
**Describe the bug**
以下の部分で変数timeoutの初期値が設定されていないため不定値になる可能性がある。

https://github.com/OpenRTM/OpenRTM-aist/blob/479bb9ae3dd5b54342f8b893172079dea5e733e2/src/lib/rtm/ExecutionContextBase.cpp#L78

**To Reproduce**

**Reproducibility**
問題が発生するかは不明。

**Expected behavior**
0に設定する。

**Screenshots or Logs**

**Environment**

**Additional context**

**Comment by n-ando** [comment]
PR #783 作成

**Comment by r-kurose** [comment]
setTimeout の第三引数は関数の結果受け取り用なので、関数が成功時にしか参照しないことから、動作上は問題無しですね。
