### ISSUE TITLE
Fluent Loggerで送信するログの仕様を考える

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#789]
**Is your feature request related to a problem? Please describe.**
現状、Fluent Loggerで出力するメッセージのrecord部分は以下のようになっている。

```
{"time":"2020-02-03 14:20:00,761","name":"fluent.manager","level":"VERBOSE","message":"0 components are marked as finalized."}
```

以下の問題点があると考えられる。

1. Fluentdのデータには既に時刻の情報が含まれているので、`time`キーは不要では？
2. 受信側から送信元を区別するための情報がない。

**Describe the solution you'd like**
(1) について、Fluentdの設定する時刻とOpenRTM-aistの設定する時刻に違いがあるのか調べる必要がある。
(2) についてはマネージャ名、プロセスID、送信元のIPアドレス等を情報に含める必要がある。

**Describe alternatives you've considered**
以下のような形式にする。

```
{
"name":"通常のログでヘッダの日時の後に付加する文字列",
"level":"ログレベル",
"manager":"マネージャ名",
"pid":"プロセスID",
"message":"ログメッセージ本体"
}
```

**Additional context**

**Comment by n-ando** [comment]
ホスト名がw借るようにしてください。
