### ISSUE TITLE
改行コードの混在

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist#84]
**Describe the bug**
一部のソースコードで改行コードLFとCRLFが混在しているため、LFに統一する必要がある。

**To Reproduce**

**Reproducibility**

**Expected behavior**

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment**

**Additional context**

**Comment by r-kurose** [comment]
変換に使ったコマンド
```
# find . | xargs file | grep CRLF,\ LF | grep UTF-8 | cut -d: -f1 | xargs nkf --oc=UTF-8-BOM --overwrite -d
# find . | xargs file | grep CRLF,\ LF | grep ASCII | cut -d: -f1 | xargs nkf --oc=ASCII --overwrite -d
```
一覧出すだけなら、 `find . | xargs file | grep CRLF,\ LF`
